baseURL = 'https://pages.github.corp.ebay.com/vat/oss-website/'
languageCode = 'en-us'
title = 'eBay Open Source Program'
# images = ['images/ebay.png']
theme = 'techdoc'

[params]

# techdoc
menu_style = "open-menu"
menu_exclusion = []

# custom_background_color='#93c9ff'
# custom_font_color='#121258'

github_repository='https://github.com/ebay/ebay.github.io'

logo = '/images/ebay-logo.png'
logo_alt_text = 'eBay'